# Generated by Django 3.0.3 on 2020-02-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200224_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
